"""
pdf_builder.py — Compile extracted slide images into a PDF with a cover page.
"""

import textwrap
from pathlib import Path
from typing import Optional
from PIL import Image, ImageDraw, ImageFont
import logging

log = logging.getLogger("pdf_builder")


def _make_cover_page(slide_titles: list[str], video_title: str, width: int = 1920, height: int = 1080) -> Image.Image:
    """Generate a simple cover page listing all slide titles as a table of contents."""
    bg = Image.new("RGB", (width, height), color=(15, 23, 42))  # dark navy
    draw = ImageDraw.Draw(bg)

    # Try to use a system font, fallback to default
    try:
        font_title = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 64)
        font_sub   = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 32)
        font_toc   = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 28)
        font_small = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 22)
    except Exception:
        font_title = font_sub = font_toc = font_small = ImageFont.load_default()

    # Accent bar
    draw.rectangle([0, 0, width, 8], fill=(99, 102, 241))

    # Title
    title_text = textwrap.shorten(video_title or "Presentation Slides", width=60, placeholder="...")
    draw.text((80, 60), title_text, fill=(255, 255, 255), font=font_title)
    draw.text((80, 155), "Extracted Slides — Table of Contents", fill=(148, 163, 184), font=font_sub)

    # Divider
    draw.line([(80, 210), (width - 80, 210)], fill=(51, 65, 85), width=2)

    # TOC entries
    y = 240
    col_width = (width - 160) // 2
    for i, title in enumerate(slide_titles, 1):
        col = 0 if i <= (len(slide_titles) + 1) // 2 else 1
        row = i - 1 if col == 0 else i - 1 - (len(slide_titles) + 1) // 2
        x = 80 + col * col_width
        ty = 240 + row * 48
        if ty > height - 80:
            break
        entry = textwrap.shorten(f"{i:>2}. {title}", width=55, placeholder="...")
        draw.text((x, ty), entry, fill=(203, 213, 225), font=font_toc)

    # Footer
    draw.text((80, height - 50), "Generated by YT2PDFS", fill=(71, 85, 105), font=font_small)
    draw.rectangle([0, height - 8, width, height], fill=(99, 102, 241))

    return bg


def build_pdf(
    image_paths: list[Path],
    slide_titles: list[str],
    output_path: Path,
    video_title: str = "Presentation",
    include_cover: bool = True,
) -> Path:
    """
    Stitch a list of PNG slide images into a single PDF file.
    Streams images page-by-page to keep RAM usage constant (< 20MB),
    preventing Out-Of-Memory crashes even for hundreds of slides from multi-hour lectures.

    Args:
        image_paths:   Ordered list of PNG file paths.
        slide_titles:  Corresponding slide title strings.
        output_path:   Where to save the output PDF.
        video_title:   Video/lecture title shown on the cover page.
        include_cover: Whether to prepend a table-of-contents cover page.

    Returns:
        Path to the created PDF.
    """
    if not image_paths:
        raise ValueError("No slide images provided to build_pdf.")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    temp_cover_path = None

    # 1. Try high-performance, low-RAM streaming via fpdf2
    try:
        from fpdf import FPDF

        # Inspect first image to determine target aspect ratio / dimensions
        first_img = Image.open(image_paths[0])
        w_px, h_px = first_img.size
        first_img.close()

        # Target dimensions in pt (standard 16:9 1280x720 or native)
        page_w = 1280
        page_h = int(1280 * (h_px / w_px)) if w_px > 0 else 720
        orientation = "L" if page_w >= page_h else "P"

        pdf = FPDF(orientation=orientation, unit="pt", format=(page_h, page_w) if orientation == "L" else (page_w, page_h))
        pdf.set_auto_page_break(False)

        total_pages = 0

        # --- Cover page ---
        if include_cover:
            try:
                cover = _make_cover_page(slide_titles, video_title, width=page_w, height=page_h)
                temp_cover_path = output_path.parent / f"_cover_tmp_{output_path.stem}.jpg"
                cover.save(str(temp_cover_path), format="JPEG", quality=90)
                pdf.add_page()
                pdf.image(str(temp_cover_path), x=0, y=0, w=page_w, h=page_h)
                total_pages += 1
            except Exception as cover_err:
                log.warning("Could not generate cover page with fpdf2: %s", cover_err)

        # --- Slide pages streamed one by one ---
        for img_path in image_paths:
            pdf.add_page()
            pdf.image(str(img_path), x=0, y=0, w=page_w, h=page_h)
            total_pages += 1

        pdf.output(str(output_path))
        log.info("PDF saved via FPDF2 streaming: %s (%d pages)", output_path, total_pages)
        return output_path

    except Exception as fpdf_err:
        log.warning("FPDF2 compilation encountered an issue (%s), falling back to Pillow...", fpdf_err)
    finally:
        if temp_cover_path and temp_cover_path.exists():
            try:
                temp_cover_path.unlink()
            except Exception:
                pass

    # 2. Fallback: Pillow compilation
    pages: list[Image.Image] = []
    if include_cover:
        try:
            cover = _make_cover_page(slide_titles, video_title)
            pages.append(cover.convert("RGB"))
        except Exception:
            pass

    for img_path in image_paths:
        img = Image.open(img_path).convert("RGB")
        pages.append(img)

    if not pages:
        raise ValueError("No pages to save.")

    first, rest = pages[0], pages[1:]
    first.save(
        str(output_path),
        format="PDF",
        save_all=True,
        append_images=rest,
        resolution=150,
    )
    log.info("PDF saved via Pillow fallback: %s (%d pages)", output_path, len(pages))
    return output_path
