name = "yt2pdfs"
main = "worker.js"
compatibility_date = "2024-09-23"
workers_dev = true

routes = [
  { pattern = "yt2pdfs.com/*", zone_name = "yt2pdfs.com" },
  { pattern = "www.yt2pdfs.com/*", zone_name = "yt2pdfs.com" }
]

[triggers]
crons = ["*/30 * * * *"]

[assets]
directory = "./static"
binding = "ASSETS"
not_found_handling = "404-page"

[vars]
BACKEND_URL = "https://yt2pdf-214301889618.europe-west1.run.app"
